image: debian/stretch

sources:
  - https://git.sr.ht/~awwx/ame

tasks:
  - install_racket: |
      wget -nv https://mirror.racket-lang.org/installers/7.1/racket-7.1-x86_64-linux.sh
      sudo sh racket-7.1-x86_64-linux.sh --unix-style --dest /usr/local
      racket -v

  - test: |
      ls
      cd ame
      ./test
