image: debian/stretch

sources:
  - https://git.sr.ht/~awwx/ame

tasks:
  - install_racket: |
      wget -nv https://s3.amazonaws.com/awwx.ws/mirror/racket-7.1-x86_64-linux.sh
      sudo sh racket-7.1-x86_64-linux.sh --unix-style --dest /usr/local
      racket -v

  - test: |
      cd ame
      ./test
