image: debian/stretch

sources:
  - https://git.sr.ht/~awwx/ame

tasks:
  - install_racket: |
      wget -nv https://download.racket-lang.org/releases/7.1/installers/racket-minimal-7.1-x86_64-linux.sh
      sudo sh racket-7.1-minimal-x86_64-linux.sh --unix-style --dest /usr/local
      racket -v

  - test: |
      cd ame
      ./test
