#!/bin/bash
set -e

# echo '=============== racket unit tests'
# (cd rkt; ./unit_tests)

echo '=============== xcompile'
(cd xcompile; racket -f expand.scm)

echo '=============== load phase 2 in racket with inline tests'
racket rkt/test-inline.rkt

echo '=============== run all tests individually'
racket -tm rkt/runtests.rkt
