(use simple-equals)

(equals (and)         t)
(equals (and nil)     nil)
(equals (and 1)       1)
(equals (and nil 1)   nil)
(equals (and 1 nil)   nil)
(equals (and 1 2)     2)
(equals (and nil 1 2) nil)
(equals (and 1 2 nil) nil)
(equals (and 1 2 3)   3)
