(use equals or)

(equals (or)             nil)
(equals (or nil)         nil)
(equals (or 1)           1)
(equals (or nil nil)     nil)
(equals (or nil 1)       1)
(equals (or 1 nil)       1)
(equals (or 1 2)         1)
(equals (or nil nil nil) nil)
(equals (or nil nil 1)   1)
(equals (or nil 1 nil)   1)
(equals (or nil 1 2)     1)
