(use arcbase afn quasiquote)

(mac caselet (var expr . args)
  (let ex (afn (args)
            (if (no (cdr args))
                (car args)
                `(,if (,is ,var ',(car args))
                       ,(cadr args)
                       ,(self (cddr args)))))
    `(,let ,var ,expr ,(ex args))))
