(use simple-equals alist)

(equals (alist nil)     t)
(equals (alist '(a))    t)
(equals (alist '(a b))  t)
(equals (alist 'foo)    nil)
(equals (alist car)     nil)
(equals (alist 123)     nil)
(equals (alist "abc")   nil)
(equals (alist #\A)     nil)
(equals (alist (table)) nil)
