(use true or)

(true (is2 (or)             nil))
(true (is2 (or nil)         nil))
(true (is2 (or 1)           1))
(true (is2 (or nil nil)     nil))
(true (is2 (or nil 1)       1))
(true (is2 (or 1 nil)       1))
(true (is2 (or 1 2)         1))
(true (is2 (or nil nil nil) nil))
(true (is2 (or nil nil 1)   1))
(true (is2 (or nil 1 nil)   1))
(true (is2 (or nil 1 2)     1))
